# Independent fission yield sample production

In [1]:
import numpy as np
import pandas as pd

In [2]:
import sandy

### Retrieve nuclear data information

In [3]:
e = 0.0253
zam = 922350
tape = sandy.get_endf6_file('jeff_33','nfpy', zam)

In [4]:
tape_rdd = sandy.get_endf6_file("jeff_33", "decay", "all")
decay_data = sandy.DecayData.from_endf6(tape_rdd)

In [5]:
nfpy = sandy.Fy.from_endf6(tape)
nfpy.data.set_index(["MAT", "MT", "ZAM", "ZAP"]).head()

                            E        FY       DFY
MAT  MT  ZAM    ZAP
9228 454 922350 10010  0.0253  0.000017  0.000003
                10020  0.0253  0.000008  0.000002
                10030  0.0253  0.000108  0.000006
                20030  0.0253  0.000000  0.000000
                20040  0.0253  0.001700  0.000081

### Obtain covariance matrix

Assuming the uncertaities equal to the standard deviations, it is possible to build the diagonal covariance matrix as follows:

In [6]:
fy_stdev = nfpy.data.query(f"ZAM=={zam} & E=={e} & MT==454").set_index('ZAP').DFY
cov = sandy.CategoryCov.from_stdev(fy_stdev)
cov.data.head().T.head()

ZAP           10010         10020         10030  20030         20040
ZAP
10010  8.692473e-12  0.000000e+00  0.000000e+00    0.0  0.000000e+00
10020  0.000000e+00  5.948233e-12  0.000000e+00    0.0  0.000000e+00
10030  0.000000e+00  0.000000e+00  3.438063e-11    0.0  0.000000e+00
20030  0.000000e+00  0.000000e+00  0.000000e+00    0.0  0.000000e+00
20040  0.000000e+00  0.000000e+00  0.000000e+00    0.0  6.617334e-09

This procedure handles relative covariance matrices. SANDY can work with relative or absolute covariance matrices thanks to the `relative` kwarg option inserted in `sandy.CategoryCov.sampling()` method. To relativize the covariance matrix it is possible to use the so called "sandwich rule" (implemented in `sandy.CategoryCov.sandwich()`), where the diagonal sensitivity matrix $S$ will be equal to the collection of the best estimates of the independent fission yields.

In [7]:
S = np.diag(1 / nfpy.data.query(f"ZAM=={zam} & E=={e} & MT==454").set_index("ZAP").FY)
S[S == np.inf] = 0

In [8]:
idx = cov.data.index
cov_relative = sandy.CategoryCov(pd.DataFrame(cov.sandwich(S).data.values, index=idx, columns=idx))
cov_relative.data.head().T.head()

ZAP       10010   10020     10030  20030    20040
ZAP
10010  0.029692  0.0000  0.000000    0.0  0.00000
10020  0.000000  0.0843  0.000000    0.0  0.00000
10030  0.000000  0.0000  0.002948    0.0  0.00000
20030  0.000000  0.0000  0.000000    0.0  0.00000
20040  0.000000  0.0000  0.000000    0.0  0.00229

### Obtain perturbation coefficients

In [9]:
nsmp = 500
coeff = cov_relative.sampling(nsmp)